name: anbox
version: 1
summary: Android in a Box
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
confinement: devmode
grade: devel

apps:
  anbox:
    command: bin/anbox-wrapper.sh
  container-manager:
    command: bin/container-manager.sh start
    stop-command: bin/container-manager.sh stop
    daemon: simple

parts:
  android-images:
    plugin: copy
    source: android-images
    files:
      android.img: android.img
  kernel-modules:
    plugin: dump
    source: kernel
  anbox-common:
    plugin: copy
    source: .
    files:
      scripts/snap-wrapper.sh: bin/anbox-wrapper.sh
      scripts/container-manager.sh: bin/container-manager.sh
      scripts/anbox-bridge.sh: bin/anbox-bridge.sh
      scripts/classic: bin/classic
      scripts/classic-create: bin/classic-create
      scripts/classic-reset: bin/classic-reset
    snap:
      - bin/anbox-bridge.sh
      - bin/anbox-wrapper.sh
      - bin/container-manager.sh
      - bin/classic
      - bin/classic-create
      - bin/classic-reset
  apparmor:
    plugin: nil
    stage-packages:
      - apparmor
  lxc:
    source: git://github.com/morphis/lxc
    source-branch: snappy-support
    build-packages:
      - libapparmor-dev
      - libcap-dev
      - libgnutls28-dev
      - libseccomp-dev
      - pkg-config
    plugin: autotools
    configflags:
      - --disable-selinux
      - --disable-python
      - --disable-lua
      - --disable-tests
      - --disable-examples
      - --disable-doc
      - --disable-api-docs
      - --disable-bash
      - --disable-cgmanager
      # FIXME: Enable again once stacked AppArmor support has landed
      - --disable-apparmor
      - --disable-seccomp
      - --enable-capabilities
      - --with-rootfs-path=/var/snap/anbox/common/lxc/
    snap:
      - bin/lxc-attach
      - bin/lxc-ls
      - bin/lxc-start
      - bin/lxc-stop
      - lib/liblxc.so.1
      - lib/liblxc.so.1.2.0
      - libexec/lxc/lxc-monitord
  anbox:
    plugin: cmake
    after:
      - lxc
    source: .
    configflags:
      # FIXME: Anbox currently has some paths with hard coded prefixes. Once
      # that is fixed we can avoid using a prefix here.
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
    build-packages:
      - build-essential
      - cmake
      - cmake-data
      - debhelper
      - dbus
      - google-mock
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-log-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libcap-dev
      - libdbus-1-dev
      - libdbus-cpp-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libglib2.0-dev
      - libgtest-dev
      - libprotobuf-dev
      - libsdl2-dev
      - pkg-config
      - protobuf-compiler
    stage-packages:
      - libegl1-mesa
      - libgles2-mesa
      - libgl1-mesa-glx
      - libsdl2-2.0-0
      - libsdl2-gfx-1.0-0
    snap:
      - usr/bin/anbox
      - usr/lib/*-linux-*/
